twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name:     "%env(APP_NAME)%"
        app_url:      "%env(APP_URL)%"
        project_name: "%env(PROJECT_NAME)%"
        project_url:  "%env(PROJECT_URL)%"
        domain:       "%env(DOMAIN)%"
        webmail_url:  "%env(WEBMAIL_URL)%"
        locales:      "%supported_locales%"
