checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        mysql: 5.5
        php: 7.2
        variables:
            DATABASE_DRIVER: 'pdo_mysql'
            DATABASE_URL: 'mysql://mail_test:password@127.0.0.1:3306/mail_test'
            APP_ENV: 'test'
            APP_SECRET: '165e25e3846534bb4665d7078a851c0b'
            MAILER_URL: 'smtp://localhost:25?encryption=&auth_mode='
            MAILER_DELIVERY_ADDRESS: 'admin@example.org'
            APP_NAME: 'Userli'
            APP_URL: 'https://users.example.org/'
            PROJECT_NAME: 'example.org'
            PROJECT_URL: 'https://www.example.org/'
            DOMAIN: 'example.org'
            SENDER_ADDRESS: 'admin@example.org'
            NOTIFICATION_ADDRESS: 'monitoring@example.org'
            SEND_MAIL: 'true'
            LOCALE: 'de'
            HAS_SINA_BOX: 'false'
            MAIL_CRYPT_ENABLED: 1
    dependencies:
        before:
            - mysql -uroot -e "CREATE DATABASE mail_test;"
            - mysql -uroot -e "CREATE USER 'mail_test'@'localhost' IDENTIFIED BY 'password';"
            - mysql -uroot -e "GRANT ALL PRIVILEGES on mail_test.* to mail_test@localhost;"
        override:
            - composer install
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: 'bin/phpunit --coverage-clover=coverage.xml'
                      coverage:
                          file: 'coverage.xml'
                          format: 'clover'
                      idle_timeout: 300

filter:
    excluded_paths:
        - assets/*
        - config/*
        - bin/*
        - features/*
        - public/*
        - src/DataFixtures/*
        - tests/*
        - templates/*
        - vagrant/*
        - var/*
        - vendor/*
