App\Entity\Alias:
    properties:
        source:
            - NotNull: ~
            - Email:
                strict: true
            - App\Validator\Constraints\EmailAddress: { groups: [unique] }
            - App\Validator\Constraints\EmailLength:
                minLength: 3
                maxLength: 24

App\Entity\User:
    properties:
        email:
            - NotNull: ~
            - Email: ~
        roles:
            - NotNull: ~
            - NotBlank: ~
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~
        domain:
            - Valid: ~
    constraints:
        - App\Validator\Constraints\EmailDomain: ~

App\Form\Model\Registration:
    properties:
        email:
            - Email:
                strict: true
                message: form.invalid-email
            - App\Validator\Constraints\EmailAddress: ~
            - App\Validator\Constraints\EmailLength:
                minLength: 3
                maxLength: 32
        voucher:
            - App\Validator\Constraints\Voucher:
                exists: true
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~

App\Form\Model\PasswordChange:
    properties:
        newPassword:
            - App\Validator\Constraints\PasswordPolicy: ~

    constraints:
        - App\Validator\Constraints\PasswordChangeConstraint: ~

App\Form\Model\Delete:
    properties:
        password:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: form.password-change.wrong-password
