# StartController

index:
    path:     /
    controller: App\Controller\StartController::indexAction

password_change:
    path:     /password_change
    controller: App\Controller\StartController::passwordChangeAction

voucher_create:
    path:     /voucher_create
    controller: App\Controller\StartController::voucherCreateAction

# DeleteController

delete:
    path:     /delete
    controller: App\Controller\DeleteController::deleteAction

# SecurityController

login:
    path:     /login
    controller: App\Controller\SecurityController::loginAction

login_check:
    path:     /login_check

logout:
    path:     /logout

# RegistrationController

register:
    path:     /register
    controller: App\Controller\RegistrationController::registerAction

welcome:
    path:     /welcome
    controller: App\Controller\RegistrationController::welcomeAction

