# StartController

index:
    path:     /
    controller: App\Controller\StartController::indexAction

aliases:
    path:     /alias
    controller: App\Controller\StartController::aliasAction

vouchers:
    path:     /voucher
    controller: App\Controller\StartController::voucherAction

account:
    path:     /account
    controller: App\Controller\StartController::accountAction

# DeleteController

alias_delete:
    path:     /alias/delete/{aliasId}
    controller: App\Controller\DeleteController::deleteAliasAction

user_delete:
    path:     /user/delete
    controller: App\Controller\DeleteController::deleteUserAction

# SecurityController

login:
    path:     /login
    controller: App\Controller\SecurityController::loginAction

login_check:
    path:     /login_check

logout:
    path:     /logout

# RegistrationController

register:
    path:     /register
    controller: App\Controller\RegistrationController::registerAction

welcome:
    path:     /welcome
    controller: App\Controller\RegistrationController::welcomeAction

# RecoveryController

recovery:
    path:     /recovery
    controller: App\Controller\RecoveryController::recoveryProcessAction

user_recovery_token:
    path:     /user/recovery_token
    controller: App\Controller\RecoveryController::recoveryTokenAction
