# StartController

index:
    path:     /
    controller: App\Controller\StartController::indexAction

# DeleteController

alias_delete:
    path:     /alias/delete/{aliasId}
    controller: App\Controller\DeleteController::deleteAliasAction

user_delete:
    path:     /user/delete
    controller: App\Controller\DeleteController::deleteUserAction

# SecurityController

login:
    path:     /login
    controller: App\Controller\SecurityController::loginAction

login_check:
    path:     /login_check

logout:
    path:     /logout

# RegistrationController

register:
    path:     /register
    controller: App\Controller\RegistrationController::registerAction

welcome:
    path:     /welcome
    controller: App\Controller\RegistrationController::welcomeAction

