- hosts: all
  become: yes
  pre_tasks:
  roles:
    - manala.apt
    - nginx
    - manala.php
    - mysql
    - systemli.dovecot
    - geerlingguy.composer
    - geerlingguy.nodejs
    - oefenweb.yarn
    - andyceo.phpcsfixer
  vars:
    dovecot_disable_plaintext_auth: "no"
    dovecot_postfix_auth: true
    manala_apt_repositories:
      - sury_php
    manala_apt_repositories_exclusive: false
    manala_apt_preferences:
      - php@sury_php
    manala_apt_packages:
      - git
      - make
      - postfix
      - unzip
      - zip
    manala_php_version: 7.1
    manala_php_extensions:
      # necessary
      - apcu
      - curl
      - gd
      - sodium
      - mbstring
      - mysql
      - xml
      - zip
      # performance
      - ctype
      - intl
      # debugging
      - xdebug
    manala_php_extensions_exclusive: false
    manala_php_sapis:
      - cli
      - fpm
    nodejs_version: "8.x"
  tasks:
    - name: composer install
      composer:
        command: install
        working_dir: /vagrant
        no_dev: False
      become: true
      become_user: vagrant
