App\Entity\Alias:
  type: entity
  repositoryClass: App\Repository\AliasRepository
  table: virtual_aliases
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    creationTime:
      #name: creation_time
      type: datetime
      nullable: false
    updatedTime:
      #name: updated_time
      type: datetime
      nullable: false
    source:
      type: string
      nullable: false
    destination:
      type: string
      nullable: false
    deleted:
      type: boolean
      options:
        default: 0
  manyToOne:
    user:
      targetEntity: User
      mappedBy: user_id
    domain:
      targetEntity: Domain
      mappedBy: domain_id
      joinColumn:
        name: domain_id
        referencedColumnName: id
  indexes:
    source_deleted_idx:
      columns: ["source", "deleted"]
    destination_deleted_idx:
      columns: ["destination", "deleted"]
    user_deleted_idx:
      columns: ["user_id", "deleted"]
  lifecycleCallbacks:
    prePersist: [updateCreationTime, updateUpdatedTime]
