App\Entity\Domain:
  type: entity
  repositoryClass: App\Repository\DomainRepository
  table: virtual_domains
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    creationTime:
      type: datetime
      nullable: false
    updatedTime:
      type: datetime
      nullable: false
    name:
      type: string
      unique: true
  lifecycleCallbacks:
    prePersist: [updateCreationTime, updateUpdatedTime]
